### ISSUE TITLE
같은 이름의 columns 두개가 결합되면 결과가 tuple 이 나오는 문제

### ISSUE THREAD

**Issue by Mishuni** [ClustProject/KETIPreDataIntegration#1]
columns 이름들이 같은 경우 결과에 (co2, co2) 이런식으로 dictionary 의 key 값이 tuple 로 나오는데, 이로 인해서 나중에 dataServer 에서 해당 모듈을 쓸 때, tuple 타입의 key 를 html 페이지로 전달하지 못하는 문제가 존재합니다.

**Comment by jwmoonP** [comment]
해당 문제는 같은 컬럼을 갖는 데이터를 integration할 때 발생하는 문제로, 현재 integration은 아직 불안정하여 해당 이슈에 대한 솔루션을 고려하고 있습니다. 현재 버젼에서는 컬럼이 동일한 데이터에 대해서 인풋으로 활용하지 않도록 해주십시요.
